# Generated by Django 3.1.6 on 2021-02-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180923_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paywaysuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
