# Generated by Django 2.1.1 on 2018-10-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_auto_20181003_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='cost',
            field=models.FloatField(),
        ),
    ]
