# Generated by Django 2.1.1 on 2018-10-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0003_auto_20181003_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='useship',
            name='weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
