# Generated by Django 2.1.1 on 2018-09-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('telegram_id', models.IntegerField(unique=True)),
                ('vk_id', models.IntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
